Service.find_or_create_by(name:"Netflix")
Service.find_or_create_by(name:"Amazon Prime Video")
Service.find_or_create_by(name:"hulu")
Service.find_or_create_by(name:"Movie Theater")
Service.find_or_create_by(name:"DVD")
Service.find_or_create_by(name:"TV")
